name: httponsteroids
description: A Progressive Web Application client that fetches data from the Hacker News API
version: 0.0.1
author: Juliana Passos
homepage: https://github.com/itsencrypted/httpsonsteroids

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1


dev_dependencies:
  test: ^1.15.3


